# Generated by Django 5.2.5 on 2025-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('capacity_in_tonnes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('cargo ship', 'Cargo Ship'), ('passenger ship', 'Passenger Ship'), ('military ship', 'Military Ship'), ('icebreaker', 'Icebreaker'), ('fishing vessel', 'Fishing Vessel'), ('barge ship', 'Barge Ship')], default='cargo ship', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], default='active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
